# Generated by Django 4.0.4 on 2022-04-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_orders',
            fields=[
                ('oreder_id', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(default='confirmation pending', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='id',
            new_name='oreder_id',
        ),
    ]
