# Generated by Django 4.0.4 on 2022-04-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_image_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_no',
            field=models.CharField(default='1234567890', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
